import dog from "../assets/image/encourages/dog.png";

export const ANNOUNCEMENTS_LIST = [
  {
    id: 1,
    title: "Wyprowadzanie psa",
    image: dog,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore incidunt dignissimos, consequuntur accusamus dicta eligendi dolorem deserunt assumenda corrupti molestias explicabo illum accusantium provident commodi. Alias asperiores, eveniet repudiandae inventore ipsum nisi suscipit facere culpa nostrum in quod? Magnam, obcaecati accusantium? Aliquid ducimus accusantium earum?",
    username: "userTest",
    userId: 2,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    comments: [],
    category: "usługi",
    animal: "psy",
    city: "Warszawa",
  },
  {
    id: 2,
    title: "Wyprowadzanie kota",
    image: dog,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore incidunt dignissimos, consequuntur accusamus dicta eligendi dolorem deserunt assumenda corrupti molestias explicabo illum accusantium provident commodi. Alias asperiores, eveniet repudiandae inventore ipsum nisi suscipit facere culpa nostrum in quod? Magnam, obcaecati accusantium? Aliquid ducimus accusantium earum?",
    username: "userTest",
    userId: 2,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    comments: [],
    category: "usługi",
    animal: "koty",
    city: "Warszawa",
  },
  {
    id: 3,
    title: "Strzyżenie chomika",
    image: dog,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore incidunt dignissimos, consequuntur accusamus dicta eligendi dolorem deserunt assumenda corrupti molestias explicabo illum accusantium provident commodi. Alias asperiores, eveniet repudiandae inventore ipsum nisi suscipit facere culpa nostrum in quod? Magnam, obcaecati accusantium? Aliquid ducimus accusantium earum?",
    username: "userTest",
    userId: 2,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    comments: [],
    category: "services",
    animal: "psy",
    city: "Warszawa",
  },
  {
    id: 4,
    title: "Adopcja rybek",
    image: dog,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore incidunt dignissimos, consequuntur accusamus dicta eligendi dolorem deserunt assumenda corrupti molestias explicabo illum accusantium provident commodi. Alias asperiores, eveniet repudiandae inventore ipsum nisi suscipit facere culpa nostrum in quod? Magnam, obcaecati accusantium? Aliquid ducimus accusantium earum?",
    username: "userName",
    userId: 1,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    comments: ["Bardzo fajne rybki na obrazku"],
    category: "adoption",
    animal: "psy",
    city: "Warszawa",
  },
  {
    id: 5,
    title: "Głaskanie szynszyla",
    image: dog,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore incidunt dignissimos, consequuntur accusamus dicta eligendi dolorem deserunt assumenda corrupti molestias explicabo illum accusantium provident commodi. Alias asperiores, eveniet repudiandae inventore ipsum nisi suscipit facere culpa nostrum in quod? Magnam, obcaecati accusantium? Aliquid ducimus accusantium earum?",
    username: "userName",
    userId: 1,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    comments: [],
    category: "services",
    animal: "psy",
    city: "Warszawa",
  },
  {
    id: 6,
    title: "Nocleg dla pająków",
    image: dog,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore incidunt dignissimos, consequuntur accusamus dicta eligendi dolorem deserunt assumenda corrupti molestias explicabo illum accusantium provident commodi. Alias asperiores, eveniet repudiandae inventore ipsum nisi suscipit facere culpa nostrum in quod? Magnam, obcaecati accusantium? Aliquid ducimus accusantium earum?",
    username: "userName",
    userId: 1,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    comments: [],
    category: "hotel",
    animal: "psy",
    city: "Warszawa",
  },
  {
    id: 7,
    title: "Adopcja węża",
    image: dog,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore incidunt dignissimos, consequuntur accusamus dicta eligendi dolorem deserunt assumenda corrupti molestias explicabo illum accusantium provident commodi. Alias asperiores, eveniet repudiandae inventore ipsum nisi suscipit facere culpa nostrum in quod? Magnam, obcaecati accusantium? Aliquid ducimus accusantium earum?",
    username: "userName",
    userId: 1,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    comments: [],
    category: "adoption",
    animal: "psy",
    city: "Warszawa",
  },
  {
    id: 8,
    title: "Turlanie psa",
    image: dog,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore incidunt dignissimos, consequuntur accusamus dicta eligendi dolorem deserunt assumenda corrupti molestias explicabo illum accusantium provident commodi. Alias asperiores, eveniet repudiandae inventore ipsum nisi suscipit facere culpa nostrum in quod? Magnam, obcaecati accusantium? Aliquid ducimus accusantium earum?",
    username: "userTest",
    userId: 2,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    comments: [],
    category: "services",
    animal: "psy",
    city: "Warszawa",
  },
  {
    id: 9,
    title: "Łaskotanie psa",
    image: dog,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore incidunt dignissimos, consequuntur accusamus dicta eligendi dolorem deserunt assumenda corrupti molestias explicabo illum accusantium provident commodi. Alias asperiores, eveniet repudiandae inventore ipsum nisi suscipit facere culpa nostrum in quod? Magnam, obcaecati accusantium? Aliquid ducimus accusantium earum?",
    username: "userTest",
    userId: 2,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    comments: [],
    category: "services",
    animal: "psy",
    city: "Warszawa",
  },
];
