import imageA from "../assets/image/encourages/dog.jpg";

export const ANNOUNCEMENTS_LIST = [
  {
    id: 1,
    title: "Wyprowadzanie psa",
    image: imageA,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore ",
    username: "userTest",
    userId: 2,
    favorite: [],
    price: "4.99",
    company: null,
    rate: 4.7,
    openHours: "8-20",
    comments: [],
    information: "i dont know",
    category: "services",
    animal: "dog",
  },
  {
    id: 2,
    title: "Hotel kota",
    image: imageA,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore",
    username: "userTest",
    userId: 2,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    openHours: "8-20",
    comments: [],
    information: "i dont know",
    category: "hotel",
    animal: "cat",
  },
  {
    id: 3,
    title: "Strzyżenie chomika",
    image: imageA,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore",
    username: "userTest",
    userId: 2,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    openHours: "8-20",
    comments: [],
    information: "i dont know",
    category: "services",
    animal: "hamster",
  },
  {
    id: 4,
    title: "Adopcja rybek",
    image: imageA,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore",
    username: "userName",
    userId: 1,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    openHours: "8-20",
    comments: ["Bardzo fajne rybki na obrazku"],
    information: "i dont know",
    category: "adoption",
    animal: "fish",
  },
  {
    id: 5,
    title: "Głaskanie szynszyla",
    image: imageA,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore",
    username: "userName",
    userId: 1,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    openHours: "8-20",
    comments: [],
    information: "i dont know",
    category: "services",
    animal: "chinchilla",
  },
  {
    id: 6,
    title: "Nocleg dla pająków",
    image: imageA,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore",
    username: "userName",
    userId: 1,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    openHours: "8-20",
    comments: [],
    information: "i dont know",
    category: "hotel",
    animal: "fish",
  },
  {
    id: 7,
    title: "Adopcja węża",
    image: imageA,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore",
    username: "userName",
    userId: 1,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    openHours: "8-20",
    comments: [],
    information: "i dont know",
    category: "adoption",
    animal: "snake",
  },
  {
    id: 8,
    title: "Turlanie psa",
    image: imageA,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore",
    username: "userTest",
    userId: 2,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    openHours: "8-20",
    comments: [],
    information: "i dont know",
    category: "services",
    animal: "fish",
  },
  {
    id: 9,
    title: "Łaskotanie psa",
    image: imageA,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus quae dolor, optio qui dolore",
    username: "userTest",
    userId: 2,
    favorite: [],
    price: 4.99,
    company: null,
    rate: 4.7,
    openHours: "8-20",
    comments: [],
    information: "i dont know",
    category: "services",
    animal: "dog",
  },
];
